accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import UserEditView,passwordchangedview,displayprofile

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp, name="signup"),
    path('contactus/', views.contactus,name='contactus'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),
     name="reset_password"),
    path('edit_profile/', views.UserEditView, name="edit_profile"),
    path('show_profile/', views.displayprofile, name="show_profile"),

   # path('password/',auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html')),
    path('password/',passwordchangedview.as_view(template_name='accounts/password_change.html'), name="password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), 
     name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"), 
        name="password_reset_complete"),
    path('BlogsWrittenByYou/', views.filterByUsername,name='filterByUsername'),
    
]

blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from blog import views

app_name = 'blog'

urlpatterns = [
    path('postComment', views.postComment, name='postComment'),
    path('writeblog/', views.writeblog,name='writeblog'),
    path('editblog/<str:slug>', views.editblog,name='editblog'),
    path('showblog/<str:slug>', views.showblog,name='showblog'),
    path('showblog/<str:slug>/likes/',views.AddLike.as_view(),name='like'),
    path('showblog/<str:slug>/dislikes/',views.AddDislike.as_view(),name='dislike'),

]

blogger/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.homepage.as_view(),name='home'),
    path('', views.index,name='index'),
    path('accounts/', include('accounts.urls' ,namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('test/', views.TestPage.as_view(),name='test'),
    # path('thanks/', views.ThanksPage.as_view(),name='thanks'),
    path('groups/', include('groups.urls' ,namespace='groups')),
    path('posts/', include('posts.urls' ,namespace='posts')),
    path('blog/', include('blog.urls')),
    path('search/', views.search,name='search'),
    path('blogs', views.blogs,name='blogs'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from django.urls import include, path, re_path

from . import views

app_name='posts'

urlpatterns = [
    re_path(r"^$", views.PostList.as_view(), name="all"),
    re_path(r"new/$", views.CreatePost.as_view(), name="create"),
    re_path(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    re_path(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    re_path(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
    path('posts/<int:pk>/likes/',views.AddLike.as_view(),name='like'),
    path('posts/<int:pk>/dislikes/',views.AddDislike.as_view(),name='dislike'),
]

accounts/models.py
from django.db import models

# Create your models here.
# Models is Django ----->Table is DataBase Or Sheet

class contact(models.Model):
    sno = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    contactNo = models.CharField(max_length = 13)
    email = models.CharField(max_length = 100)
    issue = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True,blank=True)

    def __str__(self):
        return 'Message From ' + self.name


class userTags(models.Model):
    username = models.CharField(max_length=255)
    interestingTags = models.CharField(max_length=255)
    status=models.TextField(max_length=255, null=True, blank=True)
    profile_image=models.ImageField(upload_to="static/images/%y")

    def __str__(self):
        return 'Interests of ' + self.username

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth import models
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.db.models.base import Model
from accounts.models import userTags

class editprofileform(ModelForm):
    class Meta:
        model=User
        fields=("first_name","last_name", "email")
        labels={
                'first_name':'First name',
                'last_name':'last name',
                'email':'email',
        }
class extraFieldsProfileEditform(ModelForm):
    class Meta:
        model = userTags
        fields=('status','profile_image')
        labels={'status':'status',
        'profile_image':'Profile Image',
        }

accounts/views.py
# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView,UpdateView,TemplateView
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
# Create your views here.
from . import forms
from .forms import editprofileform,extraFieldsProfileEditform
from accounts.models import contact
from accounts.models import userTags
from django.contrib import messages
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.models import User 
from blog.models import blogDb

# class SignUp(CreateView):
#   form_class=forms.SignUpForm
#   success_url=reverse_lazy('login')
#   template_name='accounts/signup.html'


def SignUp(request):
    if request.method=="POST":
      # Get the post parameters
      username=request.POST['username']
      email=request.POST['email']
      pass1=request.POST['pass1']
      pass2=request.POST['pass2']
      interestingTags=request.POST['tags']

      # check for errorneous input
      if len(pass1)<8:
        messages.warning(request, " Your password must contain 8 characters")
        return redirect('accounts:signup')

      if not username.isalnum():
        messages.warning(request, " User name should only contain letters and numbers")
        return redirect('accounts:signup')

      if User.objects.filter(username=username).exists():
        # messages.error(request,'Choose Unique Title')
        messages.warning(request, ' Choose Unique username')
        return redirect('accounts:signup')


      if (pass1!= pass2):
        messages.warning(request, " Passwords do not match ☺")
        return redirect('accounts:signup')

      
      # Create the user
      myuser = User.objects.create_user(username, email, pass1)
      myuser.save()
      newusertags = userTags(username=username, interestingTags=interestingTags) 
      newusertags.save()
      messages.success(request, " Your account has been created successfully !!!")
      return redirect('accounts:login')
    else:
      return render(request, 'accounts/signup.html')

def contactus(request):
  if request.method == 'POST':
    name = request.POST['Username']
    email = request.POST['mailid']
    phoneNo = request.POST['phoneNo']
    issue = request.POST['issue']
    # print(name + email + phoneNo + issue)
    newcontact = contact(name=name, contactNo=phoneNo, email=email, issue=issue)
    newcontact.save()
    messages.success(request, 'We have received Your Mail we will contact You Soon')
  return render(request, 'accounts/contactus.html')

class passwordchangedview(PasswordChangeView):
  form_class=PasswordChangeForm  
  success_url=reverse_lazy('accounts:show_profile')


# class UserEditView(UpdateView):
#   form_class=editprofileform
#   success_url=reverse_lazy('index')
#   template_name='accounts/profile_user.html'

#   def get_object(self):
#       return self.request.user

# class displayprofile(TemplateView):
  
#   template_name='accounts/display_profile.html'
def UserEditView(request):
  initval1={
    'first_name':request.user.first_name,
    'last_name':request.user.last_name,
    'email':request.user.email,
  }
  form=editprofileform(initial=initval1)
  usertags=userTags.objects.get(username=request.user.username)
  interests=usertags.interestingTags
  initval2={
    'status':usertags.status,
    'profile_image':usertags.profile_image,
  }
  form2=extraFieldsProfileEditform(initial=initval2)
  username=request.user
  if request.method=='POST':
    first_name=request.POST.get('first_name')
    last_name=request.POST.get('last_name')
    email=request.POST.get('email')
    interestingTags=request.POST['tags']
    status=request.POST.get('status')
    if request.FILES:
      image=request.FILES['profile_image']
      usertags=userTags.objects.get(username=username)
      usertags.profile_image=image
      usertags.save()
    # print(first_name, last_name, email, status)
    user=User.objects.get(username=username)
    user.first_name=first_name
    user.last_name=last_name
    user.email=email
    user.save()

    usertags=userTags.objects.get(username=username)
    usertags.status=status
    usertags.interestingTags=interestingTags
    usertags.save()
    messages.success(request, 'Profile Updated Successfully')
    return redirect('accounts:show_profile')
  dictn={'form':form, 'username':username, 'form2':form2, 'interests':interests}
  return render(request, 'accounts/profile_user.html', context=dictn)

def displayprofile(request):
  username=request.user
  usertags=userTags.objects.get(username=username)
  context={'usertags':usertags}
  return render(request, 'accounts/display_profile.html', context)


def filterByUsername(request):
  query = request.user.username
  allBlogs = blogDb.objects.filter(author=query)
  if allBlogs.count()== 0:
    messages.warning(request, " You haven't written any blog yet !!!")
  params = {'allBlogs':allBlogs}
  return render(request,'accounts/filterByUsername.html', params)

accounts/templates/accounts/contactus.html
{% extends "base.html" %}

{%load bootstrap4%}
{%block linkcss%}

<style>
  body {
    overflow: hidden;
    background-color: rgb(9, 36, 77);
    color: white;
  }
  #contactUsForm {
    align-items: center;
    position: absolute;
    font-family: cursive;
    max-width: 700px;
    border: 2px solid rgb(224 211 211);
    border-radius: 20px
  }

  #contactUsContainer {
    display: flex;
    justify-content: center;

  }
</style>
{%endblock%}
{%block content%}
<div id="contactUsContainer">

  <div id="contactUsForm" class="container my-3 p-5" style="max-width: 800px;">
    <h3 class="text-center">Contact Us Form</h3>
    <form method="POST" action="/accounts/contactus/">
      {% csrf_token %}

      <div class="mb-3">
        <label for="Username" class="form-label">UserName</label>
        <input type="text" class="form-control" id="Username" name="Username" aria-describedby="emailHelp"
          placeholder="Username">
      </div>
      <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" name="mailid" class="form-control" id="email" placeholder="Enter Your Working Email">
      </div>
      <div class="mb-3">
        <label for="phoneNo" class="form-label">Contact No</label>
        <input type="text" name="phoneNo" class="form-control" id="phoneNo" placeholder="Enter Your Working Contact no">
      </div>
      <div class="mb-3">
        <label for="issue" class="form-label">Describe Your Issue:</label>

        <textarea name="issue" placeholder="Describe Your Issue or Suggestions in Detail" class="form-control"
          id="issue" cols="30" rows="5"></textarea>
      </div>

      <button type="submit" class="btn-sm btn-light">Submit</button>
    </form>
  </div>
</div>
{%endblock%}

accounts/templates/accounts/display_profile.html
{% extends "base.html" %}
{%load bootstrap4%}
{% block linkcss%}
{% load static%}
<link rel="stylesheet" href="{% static 'css/master.css' %} ">
<style>
    body {
      overflow-x: hidden;
      background-color: rgb(77, 70, 9);
      color: white;
    }
    #contactUsForm {
      align-items: center;
      position: absolute;
      font-family: cursive;
    }
  
    #contactUsContainer {
      display: flex;
      justify-content: center;
  
    }
    .dropbtn {
  background-color: #04AA6D;
  color: white;
  padding: 6px;
  font-size: 6px;
  border: none;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {background-color: #ddd;}

.dropdown:hover .dropdown-content {display: block;}

.dropdown:hover .dropbtn {background-color: #3e8e41;}
  </style>
{%endblock%} 
{%block content%}
<div id="contactUsContainer">

    <div id="contactUsForm" class="container">
        <div class="dropdown">
          <a type="button" class="dropbtn" style="font-size: 1rem; display: flex; align-items: center; justify-content: center;" ><img src="https://img.icons8.com/offices/2x/menu.png" width="20px" height="20px" alt="">Dashboard</a>
          <div class="dropdown-content">
              <a class="dropdown-item" href="{% url 'posts:for_user' username=user.username %}">POSTS</a>
              <!-- <a class="dropdown-item" href="{% url 'blogs' %}">BLOGS</a> -->
              <div class="dropend text-dark" style="cursor: pointer;">
                <a class="dropdown-item dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                  BLOGS
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" type="button"href="{% url 'blogs' %}">All Blogs</a></li>
                  <li><a class="dropdown-item" type="button"href="{% url 'accounts:filterByUsername' %}">Blogs Written By you</a></li>
                </ul>
              </div>
             
                <a class="dropdown-item" href="{%url 'groups:all' %}">GROUPS</a>
            </div>
          </div>
            <div class="card hovercard">
                <div class="cardheader">

                </div>
                <div class="avatar">
                    {% if usertags.profile_image %}
                    <img src="{{ usertags.profile_image.url }}" alt="" srcset="">
                    {% else %}
                    <img alt="" src="/static/images/defaultProfile.png">
                    {% endif %}
                </div>
                <div class="info">
                    <h1><strong>Welcome</strong>  {{user.username}}</h1>
                    <p>Status:   {{usertags.status}}</p>
    <h3>User Details:</h3>
       <p>First Name:  {{user.first_name}}</br></br>
        Last Name:  {{user.last_name}}</br></br>
        Email:                {{user.email}}</br></br>
        Interesting tags:  {{usertags.interestingTags}}
       </p> 
    
                </div>
                <div class="bottom">
                    <a class="btn btn-primary btn-twitter btn-sm" href="https://twitter.com">
                        <i class="fa fa-twitter"></i>
                    </a>
                    <a class="btn btn-danger btn-sm" rel="publisher"
                       href="https://linkedin.com">
                        <i class="fa fa-linkedin"></i> 
                    </a>
                    <a class="btn btn-success btn-sm" rel="publisher"
                       href="https://instagram.com">
                        <i class="fa fa-instagram"></i> 
                    </a>
                    <a class="btn btn-primary btn-sm" rel="publisher"
                       href="https://facebook.com">
                        <i class="fa fa-facebook"></i>
                    </a>
                    <a class="btn btn-warning btn-sm" rel="publisher" href="https://pinterest.com">
                        <i class="fa fa-pinterest"></i>
                    </a>
                </div>
            </div>
    
    <a href="{% url 'accounts:edit_profile'%}"> <button  class="btn-sm btn-light">Edit Profile</button></a>

    <a href="{% url 'accounts:logout'%}"> <button  class="btn-sm btn-danger">Logout</button></a>
    </br></br>
    </div>
    </div>
{%endblock%}

accounts/templates/accounts/filterByUsername.html
{%extends "base.html" %}

{% load static %}
{% block linkcss%}

<style>
    body {
        overflow-x: hidden;
        background-color: rgb(39, 39, 39);
        color: rgb(95, 93, 93);
    }

    #subContainerIndex {
        align-items: center;
        position: absolute;
        font-family: cursive;
    }

    #mainContainerIndex {
        display: flex;
        justify-content: center;
    }
</style>
{% endblock %}

{%block content%}


<div id='mainContainerIndex'>
    <div id='subContainerIndex'>
        <div>

            <div class="row" style="min-height: 100vh;">
                <div class="col-sm-8" style=" padding-left: 250px;">
                    <div class="pb-2" style="display:flex;justify-content: center; flex-direction: row;">

                        <div class="my-2">
                            <form class="form-inline" action="/search" method="get">
                                <input class="form-control" type="search" placeholder="Search" aria-label="Search"
                                    name="query" id="query" style="width:400px;" required>
                                <button class="btn btn-outline-light my-2 my-sm-0 ml-2 px-5"
                                    type="submit">Search</button>
                            </form>
                        </div>
                    </div>
                    <h5>Blogs Written By You :--</h5>
                    <div class="d-flex flex-row" style="flex-wrap: wrap; ">

                        {% for blog in allBlogs %}
                        <div class="" style="width:740px">
                            <div class="card flex-md-row mb-4 box-shadow h-md-250">
                                <div class="card-body d-flex flex-column align-items-start">
                                    <strong class="d-inline-block mb-2 text-success">written by {{blog.author}}</strong>
                                    <h3 class="mb-0">
                                        <a class="text-dark"
                                            href="{% url 'blog:showblog' slug=blog.slug %}">{{blog.title|truncatechars:35}}</a>
                                    </h3>
                                    <div class="mb-1 text-muted">{{blog.timestamp}}</div>
                                    <div class="preview">
                                        <p class="card-text mb-auto">{{ blog.blogpriority}}{{blog.content|safe|truncatechars:170}}</p>
                                    </div>
                                    <a href="{% url 'blog:showblog' slug=blog.slug %}">Continue reading</a>
                                </div>
                                <img class="card-img-right flex-auto d-none d-md-block"
                                    data-src="holder.js/200x250?theme=thumb" alt="Thumbnail [200x250]"
                                    src="{{blog.thumbnail.url}}" data-holder-rendered="true"
                                    style="width: 240px; height: 300px;border: 2px solid hidden; border-radius: 5px;margin: 1px;">
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
                <div class="col-sm-4 bg-transparent">
                    <h5>Some Common Interests:--</h5>
                    <hr>
                    <div class="text-dark d-flex mt-3" style="flex-direction: row; flex-wrap: wrap;">
                        <form action="/search" method="get" class="form-inline m-1">
                            <input class="form-control" type="hidden" placeholder="Search" aria-label="Search"
                                name="query" id="query" value="Python" style="width: 80%;">
                            <button class="btn-sm  btn-secondary" type="submit">Python</button>
                        </form>
                        <form action="/search" method="get" class="form-inline m-1">
                            <input class="form-control" type="hidden" placeholder="Search" aria-label="Search"
                                name="query" id="query" value="JavaScript" style="width: 80%;">
                            <button class="btn-sm  btn-secondary" type="submit">JavaScript</button>
                        </form>
                        <form action="/search" method="get" class="form-inline m-1">
                            <input class="form-control" type="hidden" placeholder="Search" aria-label="Search"
                                name="query" id="query" value="Python Flask" style="width: 80%;">
                            <button class="btn-sm  btn-secondary" type="submit">Python Flask</button>
                        </form>
                        <form action="/search" method="get" class="form-inline m-1">
                            <input class="form-control" type="hidden" placeholder="Search" aria-label="Search"
                                name="query" id="query" value="HTML" style="width: 80%;">
                            <button class="btn-sm  btn-secondary" type="submit">HTML</button>
                        </form>
                        <form action="/search" method="get" class="form-inline m-1">
                            <input class="form-control" type="hidden" placeholder="Search" aria-label="Search"
                                name="query" id="query" value="C++" style="width: 80%;">
                            <button class="btn-sm btn-secondary" type="submit">C++</button>
                        </form>
                        <form action="/search" method="get" class="form-inline m-1">
                            <input class="form-control" type="hidden" placeholder="Search" aria-label="Search"
                                name="query" id="query" value="Web Development" style="width: 80%;">
                            <button class="btn-sm  btn-secondary" type="submit">Web Development</button>
                        </form>
                        <form action="/search" method="get" class="form-inline m-1">
                            <input class="form-control" type="hidden" placeholder="Search" aria-label="Search"
                                name="query" id="query" value="Technology" style="width: 80%;">
                            <button class="btn-sm  btn-secondary" type="submit">Technology</button>
                        </form>
                        <form action="/search" method="get" class="form-inline m-1">
                            <input class="form-control" type="hidden" placeholder="Search" aria-label="Search"
                                name="query" id="query" value="Django" style="width: 80%;">
                            <button class="btn-sm btn-secondary" type="submit">Django</button>
                        </form>
                        <form action="/search" method="get" class="form-inline m-1">
                            <input class="form-control" type="hidden" placeholder="Search" aria-label="Search"
                                name="query" id="query" value="PHP" style="width: 80%;">
                            <button class="btn-sm  btn-secondary" type="submit">PHP</button>
                        </form>
                        <form action="/search" method="get" class="form-inline m-1">
                            <input class="form-control" type="hidden" placeholder="Search" aria-label="Search"
                                name="query" id="query" value="CSS" style="width: 80%;">
                            <button class="btn-sm  btn-secondary" type="submit">CSS</button>
                        </form>
                        <form action="/search" method="get" class="form-inline m-1">
                            <input class="form-control" type="hidden" placeholder="Search" aria-label="Search"
                                name="query" id="query" value="Machine Learning" style="width: 80%;">
                            <button class="btn-sm  btn-secondary" type="submit">Machine Learning</button>
                        </form>
                        <form action="/search" method="get" class="form-inline m-1">
                            <input class="form-control" type="hidden" placeholder="Search" aria-label="Search"
                                name="query" id="query" value="Linux" style="width: 80%;">
                            <button class="btn-sm  btn-secondary" type="submit">Linux</button>
                        </form>
                    </div>
                    <br>
                    <hr>
                    <br>
                    <br>
                    <div>
                        <h5>Services:--</h5>
                        <button class="btn-sm btn-light mx-1 my-1">Help</button>
                        <button class="btn-sm btn-light mx-1 my-1">Top Writers</button>
                        <button class="btn-sm btn-light mx-1 my-1">Privacy</button>
                        <button class="btn-sm btn-light mx-1 my-1">Terms</button>
                        <button class="btn-sm btn-light mx-1 my-1">About Us</button>
                    </div>
                </div>
            </div>
        </div>
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 mt-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
                <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                    <svg class="bi" width="30" height="24">
                        <use xlink:href="#bootstrap"></use>
                    </svg>
                </a>
                <span class="text-muted">© 2021 Blogger, Inc</span>
            </div>

            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <a class="btn btn-outline-light mx-2 btn-social-icon btn-facebook" href="#"><i
                        class="fa fa-facebook"></i></a>
                <a class="btn btn-outline-light mx-2 btn-social-icon btn-linkedin" href="#"><i
                        class="fa fa-linkedin"></i></a>
                <a class="btn btn-outline-light mx-2 btn-social-icon btn-twitter" href="http://twitter.com/"><i
                        class="fa fa-twitter"></i></a>

            </ul>
        </footer>
    </div>
</div>
{%endblock%}

{% block linkjs%}
<script src="{% static 'js/previewOfBlog.js'%}"></script>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
 {% block linkcss%}
{% load static%}
<link rel="stylesheet" href="{% static 'css/login.css' %} ">

{%endblock%} 

{%load bootstrap4%}
{%block content%}
<div id="loginContainer">
    
    <div class="mainContainerCSS">

        <div class="box">
        <div id="cssStyle" style="min-width: 700px;">

            <strong>

                <h3 class="text-center">Login</h3>
            </strong>
            <form method="POST">
                {% csrf_token %}
                {%bootstrap_form form%}
                
                <div style="display: flex; flex-direction: column;">
                    
                    <input class="mt-2 py-2" type="Submit" class="btn btn-default" value="login" style="border-radius: 10px;margin-left: 180px;
            margin-right: 180px; font-size: large; ">
                </div>
            </form>
             <div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'accounts:signup' %}" class="ml-2">Sign Up</a>
					</div>
					<div class="d-flex justify-content-center links">
						Forgot password? <a href="{% url 'accounts:reset_password' %}" class="ml-2">Reset password</a>
					</div>
			
				</div>
        </div>
    </div>
</div>
</div>
{%endblock%}

accounts/templates/accounts/password_change.html
{% extends "base.html" %}
{%load bootstrap4%}
{%block linkcss%}

<style>
	body {
		overflow-y: hidden;
	}

	#resetForm {
		align-items: center;
		position: absolute;
		font-family: cursive
	}

	#resetContainer {
		display: flex;
		justify-content: center;

	}

	.bootstrap-select>.dropdown-toggle {
		width: 200%;
	}

	.show {
		width: 600px
	}
</style>
{%endblock%}
{%block content%}
<div id="resetContainer" style="overflow-y: hidden;">

	<div class="container p-5 my-3" id="resetForm"
		style="max-width:700px; border: 2px solid rgb(224 211 211); border-radius:20px">
    <h1>Change Password</h1>
    <form method="POST">
    {%csrf_token%}
    {%bootstrap_form form%}
    <button type="submit" class="btn btn-success">Confirm</button>
</form>
        </div>
</div>
{%endblock%}

accounts/templates/accounts/profile_user.html
{%extends "base.html" %}
{%load bootstrap4%}
{%block linkcss%}

<style>
  body {
    overflow-x: hidden;
    background-color: rgb(77, 70, 9);
    color: white;
  }

  #contactUsForm {
    align-items: center;
    position: absolute;
    font-family: cursive;
    max-width: 700px;
    border: 2px solid rgb(224 211 211);
    border-radius: 20px
  }

  #contactUsContainer {
    display: flex;
    justify-content: center;

  }

  .bootstrap-select>.dropdown-toggle {
    width: 200%;
  }

  .show {
    width: 600px
  }
</style>
{%endblock%}
{%block content%}
<div id="contactUsContainer">

  <div id="contactUsForm" class="container my-3 p-5" style="max-width: 800px;">
    <h3 class="text-center">Edit Your Profile Here</h3>

    <form method="POST" style="max-width:840px" enctype="multipart/form-data">
      <label for="username">username</label>
      <input id="username" class="form-control" type="text" disabled value="{{username}}">
      <small>     You can't edit username</small>
      {%csrf_token%}
      {% bootstrap_form form %}
      {% bootstrap_form form2 %}
      <!-- container of change interesting tags -->
      <p>Interests :- <br>Currently:- {{interests}}<br>
      Change Your Interests</p>
      <select multiple data-style="bg-white px-4 py-3 mb-3 shadow-sm " id="selectpickerid" class="selectpicker w-50">
        <option>#JavaScript </option>
        <option>#Python flask </option>
        <option>#Python </option>
        <option>#C++ </option>
        <option>#Java </option>
        <option>#HTML </option>
        <option>#Bootstrap </option>
        <option>#Django </option>
        <option>#PHP </option>
      </select>
      <small>
        <ul>
          <li>Select maximum 3 tags</li>
        </ul>
      </small>
      <input id="hiddenSelected" type="hidden" name="tags">

      <!-- end of container  -->
      <a class="btn btn-sm btn-danger" href="{% url 'accounts:password' %}">change password</a>
      <button type="submit" class="btn  btn-sm btn-success">Update Profile</button>
    </form>
  </div>
</div>
{%endblock%}

{% block linkjs %}
{% load static %} 
<script src="{% static 'js/signup.js' %}"></script>
{% endblock %}