accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import UserEditView,passwordchangedview,displayprofile

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp, name="signup"),
    path('contactus/', views.contactus,name='contactus'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),
     name="reset_password"),
    path('edit_profile/', views.UserEditView, name="edit_profile"),
    path('show_profile/', views.displayprofile, name="show_profile"),

   # path('password/',auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html')),
    path('password/',passwordchangedview.as_view(template_name='accounts/password_change.html'), name="password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), 
     name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"), 
        name="password_reset_complete"),
    path('BlogsWrittenByYou/', views.filterByUsername,name='filterByUsername'),
    
]

blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from blog import views

app_name = 'blog'

urlpatterns = [
    path('postComment', views.postComment, name='postComment'),
    path('writeblog/', views.writeblog,name='writeblog'),
    path('editblog/<str:slug>', views.editblog,name='editblog'),
    path('showblog/<str:slug>', views.showblog,name='showblog'),
    path('showblog/<str:slug>/likes/',views.AddLike.as_view(),name='like'),
    path('showblog/<str:slug>/dislikes/',views.AddDislike.as_view(),name='dislike'),

]

blogger/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.homepage.as_view(),name='home'),
    path('', views.index,name='index'),
    path('accounts/', include('accounts.urls' ,namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('test/', views.TestPage.as_view(),name='test'),
    # path('thanks/', views.ThanksPage.as_view(),name='thanks'),
    path('groups/', include('groups.urls' ,namespace='groups')),
    path('posts/', include('posts.urls' ,namespace='posts')),
    path('blog/', include('blog.urls')),
    path('search/', views.search,name='search'),
    path('blogs', views.blogs,name='blogs'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from django.urls import include, path, re_path

from . import views

app_name='posts'

urlpatterns = [
    re_path(r"^$", views.PostList.as_view(), name="all"),
    re_path(r"new/$", views.CreatePost.as_view(), name="create"),
    re_path(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    re_path(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    re_path(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
    path('posts/<int:pk>/likes/',views.AddLike.as_view(),name='like'),
    path('posts/<int:pk>/dislikes/',views.AddDislike.as_view(),name='dislike'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from ckeditor.fields import RichTextField
from accounts.models import userTags

# Create your models here.
class blogDb(models.Model):
    sno = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255, unique = True)
    author = models.CharField(max_length = 100)
    slug = models.SlugField(unique = True, null = True, blank = True)
    content = RichTextField(blank=True, null=True)
    views = models.IntegerField(default=0)
    tags = models.CharField(max_length=255)
    blogpriority = models.IntegerField(default=0)
    thumbnail = models.ImageField(upload_to="static/images/%y")
    # content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True,blank=True)
    likes=models.ManyToManyField(User,related_name='blikes',blank=True)
    dislikes=models.ManyToManyField(User,related_name='bdislikes',blank=True)
    def __str__(self):
        return 'Blog written by ' + self.author
    


from blogger.utils import unique_slug_generator
from django.db.models.signals import pre_save
def pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(pre_save_receiver, sender = blogDb)




class blogComment(models.Model):
    sno = models.AutoField(primary_key = True)
    comment = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    usertags = models.ForeignKey(userTags, on_delete=models.CASCADE)
    blog = models.ForeignKey(blogDb, on_delete=models.CASCADE)
    parent = models.ForeignKey('self',on_delete=models.CASCADE, null=True)
    timestamp = models.DateTimeField(default=now)

blog/forms.py
from blog.models import blogDb
from django.forms import ModelForm


class writeBlogForm(ModelForm):
    class Meta:
        model = blogDb
        fields = ['title',  'content', 'thumbnail']
        labels = {'title':'Enter Title of Your Blog', 'content':'Write Content Of your Blog Here                                                            ', 'thumbnail':'Add thumbnail for your Blog'}        

blog/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.views import View
# Create your views here.
from blog.models import blogDb, blogComment
from blog.templatetags import extras
from blog.forms import writeBlogForm
from accounts.models import userTags

def editblog(request, slug=None):
  blog = blogDb.objects.get(slug = slug)
  initVal = {
    'title': blog.title,
    'content': blog.content,
    'thumbnail':blog.thumbnail,
  }
  form = writeBlogForm(initial=initVal)
  params={ 'form':form, 'slug':slug }
  if request.method == 'POST':
    titlepost = request.POST.get('title')
    contentpost = request.POST.get('content')
    tagspost = request.POST.get('tags')
    # Handling Change of thumbnail
    if 'thumbnail' in request.FILES:
      thumbnailpost = request.FILES['thumbnail']
      blog.thumbnail = thumbnailpost
    blog.title = titlepost
    blog.content = contentpost
    blog.tags = tagspost
    blog.save()
    blog = blogDb.objects.get(title = titlepost)
    return redirect(f"/blog/showblog/{blog.slug}")
  else:
    
    return render(request, 'editblog.html', context=params)

def writeblog(request):

  if request.method =='POST':
    title=request.POST.get('title')
    author=request.POST.get('author')
    content=request.POST.get('content')
    tags = request.POST.get('tags')
    getthumbnail = request.FILES['thumbnail']
    tagsArr=tags.split(' ')
    initVal = {'title':title, 'content':content}
    form = writeBlogForm(request.POST, request.FILES, initial = initVal)
    # some checks of form

    if blogDb.objects.filter(title=title).exists():
      # messages.error(request,'Choose Unique Title')
      params={'title':title, 'author':author,'content':content,'tagsArr':tagsArr,'form':form}
      messages.warning(request, ' Choose Unique Title')
      return render(request, 'writeBlog.html', context = params)

    else:
      newBlog=blogDb(title=title, author=author, content=content, tags=tags, thumbnail=getthumbnail)
      newBlog.save()
      blog=blogDb.objects.get(title=title)
      return redirect(f"/blog/showblog/{blog.slug}")
  else:
    form = writeBlogForm()
    params={'title':"", 'author':"",'content':"", 'form':form}
    return render(request, 'writeBlog.html', context = params)



def showblog(request, slug=None):
  blog = blogDb.objects.get(slug = slug)
  comments = blogComment.objects.filter(blog=blog, parent=None)
  replies = blogComment.objects.filter(blog=blog).exclude(parent=None)
  blog.views = blog.views +1 
  blog.save();
  # Here I will create Dictionary for replies
  replyDict = {}
  for reply in replies:
    if reply.parent.sno not in replyDict.keys():
      replyDict[reply.parent.sno]=[reply]
    else:
      replyDict[reply.parent.sno].append(reply)


  tags = blog.tags
  tagsArr=tags.split(' ')

  context={
    'blog':blog, 'comments':comments, 'replyDict':replyDict, 'tagsArr':tagsArr
  }
  return render(request, 'showBlog.html', context)





def postComment(request):
  if request.method =='POST':
    comment = request.POST.get('comment')
    user = request.user
    uname = user.username
    blogSno = request.POST.get('blogSno')
    blog = blogDb.objects.get(sno=blogSno)
    # usertags = userTags.objects.get(username=user.username)
    # if usertags.profile_image:
    #   userImageUrl = usertags.profile_image.url
    # else :
    #   userImageUrl = "/static/images/defaultProfile.png"
    usertags = userTags.objects.get(username=uname) 
    parentSno = request.POST.get('parentSno')
    if parentSno=="":
      comment = blogComment(comment=comment, user=user, blog=blog,usertags=usertags)
      comment.save()
      messages.success(request, ' Your Comment posted Successfully')
    else:
      parent = blogComment.objects.get(sno=parentSno)
      comment = blogComment(comment=comment, user=user, blog=blog, parent=parent,usertags=usertags)

      comment.save()
      messages.success(request, ' Your Reply To Comment Posted Succeefully')

  return redirect(f"/blog/showblog/{blog.slug}")

class AddLike(LoginRequiredMixin, View):
    def post(self, request,slug, *args, **kwargs):
        post = blogDb.objects.get(slug=slug)

        is_dislike = False

        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if is_dislike:
            post.dislikes.remove(request.user)

        is_like = False

        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if not is_like:
            post.likes.add(request.user)

        if is_like:
            post.likes.remove(request.user)
        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)

class AddDislike(LoginRequiredMixin, View):
    def post(self, request, slug, *args, **kwargs):
        post = blogDb.objects.get(slug=slug)

        is_like = False

        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if is_like:
            post.likes.remove(request.user)

        is_dislike = False

        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if not is_dislike:
            post.dislikes.add(request.user)

        if is_dislike:
            post.dislikes.remove(request.user)

        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v12.0"
    nonce="tOQNA2vN"></script>
  <title>Blogger</title>
  <link rel="stylesheet" href="{% static 'bg/css/master.css'%}">

  {% block linkcss%}{% endblock %}
  <style>
    ::-webkit-scrollbar{
  width: 12px;

    }
::-webkit-scrollbar-thumb{
  background: aqua;
  border-radius: 10px;
}

  </style>
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-secondary techfont" role="navigation" id="navbar">
    <div class="container d">
      <a class="navbar-brand mynav" href="{% url 'index' %}"><img
          src="https://upload.wikimedia.org/wikipedia/commons/c/c7/B-logo-1.png" alt="no pic" height="50px"
          width="70px"><b>logger</b></a>

      <ul class="nav navbar-nav navbar-right">

        {% block searchForm%}{% endblock %}



        {% if user.is_authenticated %}
        <div class="navbar-nav ml-auto">
          <a href="{% url 'blogs' %}" class="nav-item nav-link active"><i class="fa fa-home"> </i><span>Blogs</span></a>
          
          <a href="{%url 'groups:all' %}" class="nav-item nav-link"><i class="fa fa-users"></i><span>Room</span></a>
          <a href="{% url 'accounts:contactus'  %}" class="nav-item nav-link"><i
              class="fa fa-exclamation-triangle"></i><span>Contact Us</span></a>
              <a href="{% url 'accounts:show_profile' %}" class="nav-item nav-link"><i
                class="fa fa-exclamation-triangle"></i><span>Profile</span></a>
            
        </div>

       

        {% else %}
        <a href="{%url 'groups:all' %}" class="nav-item nav-link"><i class="fa fa-users"></i><span>Room</span></a>
        <li><a href="{% url 'accounts:login'  %}" class="nav-item nav-link"><i class="fa fa-sign-in"></i>Log in</a></li>
        <li><a href="{% url 'accounts:signup'  %}" class="nav-item nav-link"><i class="fa fa-user-plus"></i>Sign Up</a>
        </li>
        <a href="{% url 'accounts:contactus'  %}" class="nav-item nav-link"><i
            class="fa fa-exclamation-triangle"></i><span>Contact Us</span></a>

        {% endif %}
      </ul>
    </div>
  </nav>
  {% for message in messages%}
  <div style="display: flex; align-items: center;justify-content: center;">

    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert" style="min-width: 800px;">
      <strong style="font-size: 1.2rem;">Message</strong> {{message}}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
  {% endfor%}

  <div class="container py-2">{%block content%}{% endblock %}</div>
  <canvas id="canvas"></canvas>


</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/js/bootstrap-select.min.js"></script>

<!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
  integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
  integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
  integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="{% static "bg/js/master.js" %}" type="text/javascript"></script>
<script>
  $("#myModal").on("shown.bs.modal", function () {
    $("#myInput").trigger("focus");
  });
</script>
{% block linkjs%}{% endblock %}

</html>

templates/index.html
{%extends "base.html" %}

{% block searchForm%}

<!-- <form action="/search" method="get" class="form-inline my-2 my-lg-0">
  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query" id="query">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form> -->
{% endblock %}
{% load static %}
{% block linkcss%}

<style>
  body{
    overflow-x: hidden;
    background-color: rgb(39, 39, 39);
    color: rgb(95, 93, 93);
  } 
  #subContainerIndex {
    align-items: center;
    position: absolute;
    font-family: cursive;
  }

  #mainContainerIndex {
    display: flex;
    justify-content: center;
  }
  </style>
<link rel="stylesheet" href="{%static 'css/button.css'%}">
{% endblock %}

{%block content%}
<div id='mainContainerIndex'>
  <div id='subContainerIndex'>
  <div class="kl text-center" style="padding-top: 200px; padding-bottom: 200px;">
    <h1><strong>Welcome to Blogger</strong> </h1>
   <div class="write" >
    
    <h2>Always had a thought to start a Blog?</h2>
    <h3>We are here to help u follow your passion.</h3>
    <h3>Get Started now to create your own Blog!!</h3>
    </div>
  </div>


<div style="padding-bottom: 70px;">

  {% if user.is_authenticated %}
  <a href="blog/writeblog/">
    <p id="startWritingBtn">
      <button id="button" class="BT-OH-BR-R6-NF-FH-FP-TU-PT">
        <canvas id="canvas"></canvas>
        <hover></hover>
        <span><strong> Start Writing</strong>
         
        </span>

      </button>

    </p>
  </a>
  {%else%}
  <a href="accounts/login/">
    <p id="startWritingBtn">
      <button id="button" class="BT-OH-BR-R6-NF-FH-FP-TU-PT">
        <canvas id="canvas"></canvas>
        <hover></hover><strong><span>Get Started</span></strong>
      </button>

    </p>
  </a>
  {%endif%}
</div>
<br><hr><br>

<div>

  <div class="row">
    <!-- <div class="col-sm-8" style="max-height: 670px;overflow-y:scroll; padding-left: 150px;"> -->
    <div class="col-sm-8" style="padding-left: 270px;">
            <!--   On Index Page We r Showing Only 10 Recent Blogs   -->
      <h4 class="text-center pr-5 pb-3" >Some Trending Blogs</h4>
      <div class="d-flex flex-row" style="flex-wrap: wrap; ">

        {% for blog in allBlogs %}
        {% if blog.thumbnail %}
        <div class="" style="width:740px">
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-success">written by {{blog.author}}</strong>
              <h3 class="mb-0">
                <a class="text-dark" href="{% url 'blog:showblog' slug=blog.slug %}">{{blog.title|truncatechars:35}}</a>
              </h3>
              <div class="mb-1 text-muted">{{blog.timestamp}}</div>
              <div class="preview">
                <p class="card-text mb-auto">{{blog.content|safe|truncatechars:180}}</p>
              </div>
              <a href="{% url 'blog:showblog' slug=blog.slug %}">Continue reading</a>
            </div>
            <img class="card-img-right flex-auto d-none d-md-block" data-src="holder.js/200x250?theme=thumb"
              alt="Thumbnail [200x250]"
              src="{{blog.thumbnail.url}}"
              data-holder-rendered="true" style="width: 240px; height: 300px;border: 2px solid hidden; border-radius: 5px;margin: 1px;">
          </div>
        </div>
        {% else %}
        <div class="" style="width:740px">
          <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-success">written by {{blog.author}}</strong>
              <h3 class="mb-0">
                <a class="text-dark" href="{% url 'blog:showblog' slug=blog.slug %}">{{blog.title|truncatechars:35}}</a>
              </h3>
              <div class="mb-1 text-muted">{{blog.timestamp}}</div>
              <div class="preview">
                <p class="card-text mb-auto">{{blog.content|safe|truncatechars:170}}</p>
              </div>
              <a href="{% url 'blog:showblog' slug=blog.slug %}">Continue reading</a>
            </div>
            <img class="card-img-right flex-auto d-none d-md-block" data-src="holder.js/200x250?theme=thumb"
              alt="Thumbnail [200x250]"
              src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22200%22%20height%3D%22250%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20200%20250%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_17ca711f406%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A13pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_17ca711f406%22%3E%3Crect%20width%3D%22200%22%20height%3D%22250%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2256.1953125%22%20y%3D%22131%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
              data-holder-rendered="true" style="width: 240px; height: 300px;">
          </div>
        </div>
        {%endif%}
        {% endfor %}

      </div>
    </div>
    <div class="col-sm-4 bg-transparent">
      <h5>Some Common Interests:--</h5>
      <hr>
      <div class="text-dark d-flex mt-3" style="flex-direction: row; flex-wrap: wrap;">
        <form action="/search" method="get" class="form-inline m-1">
          <input class="form-control" type="hidden" placeholder="Search" aria-label="Search" name="query" id="query"
            value="Python" style="width: 80%;">
          <button class="btn-sm  btn-secondary" type="submit">Python</button>
        </form>
        <form action="/search" method="get" class="form-inline m-1">
          <input class="form-control" type="hidden" placeholder="Search" aria-label="Search" name="query" id="query"
            value="JavaScript" style="width: 80%;">
          <button class="btn-sm  btn-secondary" type="submit">JavaScript</button>
        </form>
        <form action="/search" method="get" class="form-inline m-1">
          <input class="form-control" type="hidden" placeholder="Search" aria-label="Search" name="query" id="query"
            value="Python Flask" style="width: 80%;">
          <button class="btn-sm  btn-secondary" type="submit">Python Flask</button>
        </form>
        <form action="/search" method="get" class="form-inline m-1">
          <input class="form-control" type="hidden" placeholder="Search" aria-label="Search" name="query" id="query"
            value="HTML" style="width: 80%;">
          <button class="btn-sm  btn-secondary" type="submit">HTML</button>
        </form>
        <form action="/search" method="get" class="form-inline m-1">
          <input class="form-control" type="hidden" placeholder="Search" aria-label="Search" name="query" id="query"
            value="C++" style="width: 80%;">
          <button class="btn-sm btn-secondary" type="submit">C++</button>
        </form>
        <form action="/search" method="get" class="form-inline m-1">
          <input class="form-control" type="hidden" placeholder="Search" aria-label="Search" name="query" id="query"
            value="Web Development" style="width: 80%;">
          <button class="btn-sm  btn-secondary" type="submit">Web Development</button>
        </form>
        <form action="/search" method="get" class="form-inline m-1">
          <input class="form-control" type="hidden" placeholder="Search" aria-label="Search" name="query" id="query"
            value="Technology" style="width: 80%;">
          <button class="btn-sm  btn-secondary" type="submit">Technology</button>
        </form>
        <form action="/search" method="get" class="form-inline m-1">
          <input class="form-control" type="hidden" placeholder="Search" aria-label="Search" name="query" id="query"
            value="Django" style="width: 80%;">
          <button class="btn-sm btn-secondary" type="submit">Django</button>
        </form>
        <form action="/search" method="get" class="form-inline m-1">
          <input class="form-control" type="hidden" placeholder="Search" aria-label="Search" name="query" id="query"
            value="PHP" style="width: 80%;">
          <button class="btn-sm  btn-secondary" type="submit">PHP</button>
        </form>
        <form action="/search" method="get" class="form-inline m-1">
          <input class="form-control" type="hidden" placeholder="Search" aria-label="Search" name="query" id="query"
            value="CSS" style="width: 80%;">
          <button class="btn-sm  btn-secondary" type="submit">CSS</button>
        </form>
        <form action="/search" method="get" class="form-inline m-1">
          <input class="form-control" type="hidden" placeholder="Search" aria-label="Search" name="query" id="query"
            value="Machine Learning" style="width: 80%;">
          <button class="btn-sm  btn-secondary" type="submit">Machine Learning</button>
        </form>
        <form action="/search" method="get" class="form-inline m-1">
          <input class="form-control" type="hidden" placeholder="Search" aria-label="Search" name="query" id="query"
            value="Linux" style="width: 80%;">
          <button class="btn-sm  btn-secondary" type="submit">Linux</button>
        </form>
      </div>
      <br>
      <hr>
      <br>
      <br>
      <div>
        <h5>Services:--</h5>
        <button class="btn-sm btn-light mx-1 my-1">Help</button>
        <button class="btn-sm btn-light mx-1 my-1">Top Writers</button>
        <button class="btn-sm btn-light mx-1 my-1">Privacy</button>
        <button class="btn-sm btn-light mx-1 my-1">Terms</button>
        <button class="btn-sm btn-light mx-1 my-1">About Us</button>
      </div>
    </div>
  </div>
</div>

<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 mt-4 border-top">
  <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
          <svg class="bi" width="30" height="24">
              <use xlink:href="#bootstrap"></use>
          </svg>
      </a>
      <span class="text-muted">© 2021 Blogger, Inc</span>
  </div>

  <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <a class="btn btn-outline-light mx-2 btn-social-icon btn-facebook" href="#"><i
              class="fa fa-facebook"></i></a>
      <a class="btn btn-outline-light mx-2 btn-social-icon btn-linkedin" href="#"><i
              class="fa fa-linkedin"></i></a>
      <a class="btn btn-outline-light mx-2 btn-social-icon btn-twitter" href="http://twitter.com/"><i
              class="fa fa-twitter"></i></a>

  </ul>
</footer>
</div>
</div>
{%endblock%}

{% block linkjs%}
<script src="{% static 'js/previewOfBlog.js'%}"></script>
<script src="{% static 'js/button.js'%}"></script>
</body>
{% endblock %}