blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from blog import views

app_name = 'blog'

urlpatterns = [
    path('postComment', views.postComment, name='postComment'),
    path('writeblog/', views.writeblog,name='writeblog'),
    path('editblog/<str:slug>', views.editblog,name='editblog'),
    path('showblog/<str:slug>', views.showblog,name='showblog'),
    path('showblog/<str:slug>/likes/',views.AddLike.as_view(),name='like'),
    path('showblog/<str:slug>/dislikes/',views.AddDislike.as_view(),name='dislike'),

]

blogger/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.homepage.as_view(),name='home'),
    path('', views.index,name='index'),
    path('accounts/', include('accounts.urls' ,namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('test/', views.TestPage.as_view(),name='test'),
    # path('thanks/', views.ThanksPage.as_view(),name='thanks'),
    path('groups/', include('groups.urls' ,namespace='groups')),
    path('posts/', include('posts.urls' ,namespace='posts')),
    path('blog/', include('blog.urls')),
    path('search/', views.search,name='search'),
    path('blogs', views.blogs,name='blogs'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from django.urls import include, path, re_path

from . import views

app_name='posts'

urlpatterns = [
    re_path(r"^$", views.PostList.as_view(), name="all"),
    re_path(r"new/$", views.CreatePost.as_view(), name="create"),
    re_path(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    re_path(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    re_path(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
    path('posts/<int:pk>/likes/',views.AddLike.as_view(),name='like'),
    path('posts/<int:pk>/dislikes/',views.AddDislike.as_view(),name='dislike'),
]

posts/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.
from django.conf import settings
from django.urls import reverse

from groups.models import  Group

from django.contrib.auth import get_user_model
User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts",on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = RichTextField(blank=True, null=True)
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name="posts",null=True, blank=True,on_delete=models.CASCADE)
    likes=models.ManyToManyField(User,related_name='likes',blank=True)
    dislikes=models.ManyToManyField(User,related_name='dislikes',blank=True)

    def _str_(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = self.message
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "posts:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )
   
    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "message"]

posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic
from .models import Post
from braces.views import SelectRelatedMixin
from django.views import View
from . import forms
from . import models

from django.contrib.auth import get_user_model
User = get_user_model()


class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ("user", "group")


class UserPosts(generic.ListView):
    model = models.Post
    template_name = "posts/user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    # form_class = forms.PostForm
    fields = ('message','group')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ("user", "group")
    success_url = reverse_lazy("posts:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

class AddLike(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)

        is_dislike = False

        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if is_dislike:
            post.dislikes.remove(request.user)

        is_like = False

        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if not is_like:
            post.likes.add(request.user)

        if is_like:
            post.likes.remove(request.user)

        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)

class AddDislike(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)

        is_like = False

        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break

        if is_like:
            post.likes.remove(request.user)

        is_dislike = False

        for dislike in post.dislikes.all():
            if dislike == request.user:
                is_dislike = True
                break

        if not is_dislike:
            post.dislikes.add(request.user)

        if is_dislike:
            post.dislikes.remove(request.user)

        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)

posts/templates/posts/_post.html
<div class="card" style="background-color: antiquewhite;">
<div class="jumbotron" style="background-color: rgb(39, 39, 39);">
	<h2 style="color:rgb(228, 72, 72);font-size: 23px; text-align:left;">{{ post.message_html|safe }}</h2>
	<div class="media-body">
		<strong>--> author: {{ post.user.username }}</strong>
		<h4 class="media-heading" style="color:rgb(180, 143, 143);font-size: 19px;">
			<span class="username">->blog handle:<a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></span>
			<time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a></time>
			{% if post.group %}
			<span class="group-name">posted in <a href="#">{{ post.group.name }}</a></span>
			{% endif %}
		</h4>




		<div class="media-footer hg">
			{% if user.is_authenticated and post.user == user and not hide_delete %}
				<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
					<span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
			{% endif %}
		</div>
		<div class="form-inline my-2 my-lg-0" >
			<form method="POST" action="{% url 'posts:like' post.pk %}">
				{% csrf_token %}
				<input type="hidden" name="next" value="{{ request.path }}">
				<button style="background-color: transparent;color: rgb(197, 158, 158); border: none; box-shadow: none;" type="submit">
					<img src="/static/images/likeicon.png" width="50px" height="50px">{{ post.likes.all.count }}
				</button>
			</form>
		
			<form method="POST" action="{% url 'posts:dislike' post.pk %}">
				{% csrf_token %}
				<input type="hidden" name="next" value="{{ request.path }}">
				<button style="background-color: transparent;color: rgb(197, 158, 158); border: none; box-shadow: none;" type="submit">
				<img src="/static/images/dislikeicon.png" width="40px" height="40px" alt="">	{{ post.dislikes.all.count }}
				</button>
			</form>
		  </div>
	</div>
</div>

posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
<div class="posts-page">
	<div class="container">
		<div class="row">
			{% block prepost%}{% endblock %}
			{% block post_content %}{% endblock %}
			{% block post_post%}{% endblock %}
		</div>
	</div>
</div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}
{% block post_content %}

	<style>.d {
	 
		background-color: rgb(248, 238, 238);
		animation-name: example;
		animation-duration: 4s;
	  }
	  
	  @keyframes example {
		0%   {background-color: rgb(204, 156, 156);}
		25%  {background-color: rgb(138, 138, 54);}
		50%  {background-color: rgb(78, 78, 119);}
		100% {background-color: rgb(180, 223, 180);}
	  }
	</style>
	


<div class="alert alert-danger d" role="alert">
	<h3>Are you sure about delete this post?</h3>
  </div>
<h3><br></h3>
<div class="alert alert-dark">
<div class="posts">
	{% include "posts/_post.html" with post=object hide_delete=True %}
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-default">Cancel</a>
</form>
</div>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<div class="col-md-8">
    {% include "posts/_post.html" %}
</div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}

{% block linkcss%}

{% load static%}
{%endblock%} 

{% load bootstrap4 %}

{% block post_content %}
<h4>Create New Post</h4>
<form method="POST" action="{% url 'posts:create' %}" id="postForm">
	{% csrf_token %}
	{{ form.media }}
	{% bootstrap_form form %}
	<input type="submit" value="Post" class="btn btn-primary btn-large">
</form>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}

{% block pre_post_content %}
<div class="col-md-4">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Groups</h5>
			<ul class="list-unstyled">
				{# {% get_user_groups as user_groups %}#}
				{% for member_group in get_user_groups %}
				<li class="group li-with-bullet">
					<a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
				</li>
				{% endfor %}

			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All groups</h5>
			<ul class="list-unstyled">
				{# {% get_other_groups as other_groups %}#}
				{% for other_group in get_other_groups %}
					<li class="group li-with-bullet"><a href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
				{% endfor %}
			</ul>
			



		</div>
	</div>
</div>
{% endblock %}
{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
  {% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class="col-md-4">
	<h1>@{{ post_user.username }}</h1>
	<p>Post History</p>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
		{% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}